// src/scheduler.vue
<template>
  <section class="event-scheduler-shift-week-demo">
    <div class="event-scheduler-shift-week-main">
      <revogr-scheduler-header
        :model.prop="headerModel"
        @scheduler-header-calendar-change="handleHeaderCalendarChange"
        @scheduler-header-navigate="handleHeaderNavigate"
        @scheduler-header-view-change="handleHeaderViewChange"
        @scheduler-header-workspace-change="handleHeaderWorkspaceChange"
      />
      <RevoGrid
        v-if="workspaceView === 'table'"
        class="event-scheduler-shift-week-table"
        hide-attribution
        readonly
        :theme="isDark ? 'darkMaterial' : 'material'"
        :plugins="tablePlugins"
        :filter="{}"
        :source="filteredTableRows"
        :columns="tableColumns"
      />
      <template v-else>
        <RevoGrid
          class="event-scheduler-shift-week-grid"
          hide-attribution
          :theme="isDark ? 'darkMaterial' : 'material'"
          :plugins="plugins"
          :source="schedulerEvents"
          :columns="columns"
          :event-scheduler.prop="schedulerConfig"
          :event-scheduler-resources.prop="resources"
          @gridedit="handleSchedulerEvents"
          @event-scheduler-before-event-select="handleBeforeEventSelect"
          @event-scheduler-navigate-request="handleNavigateRequest"
          @event-scheduler-open-shift-assign-request="handleOpenShiftAssignRequest"
          @event-scheduler-resource-reassign-request="handleResourceReassignRequest"
          @event-scheduler-view-request="handleViewRequest"
        />
      </template>
    </div>
    <revogr-scheduler-dialog
      :model.prop="dialogModel"
      @scheduler-dialog-close="closeNewEvent"
      @scheduler-dialog-submit="handleDialogSubmit"
    />
  </section>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import RevoGrid from '@revolist/vue3-datagrid';
import { EventSchedulerPlugin, type EventSchedulerEntityId, type EventSchedulerEventSelectedDetail, type EventSchedulerOpenShiftAssignRequestDetail, type EventSchedulerResourceReassignRequestDetail } from '@revolist/scheduler';
import { AdvanceFilterPlugin, ColumnStretchPlugin, RowOddPlugin, applySourceChanges } from '@revolist/revogrid-pro';
import { currentTheme, observeCurrentTheme } from './shared/theme';
import {
  createShiftWeekAssignedOpenShift,
  createShiftWeekConfig,
  createShiftWeekEvents,
  createShiftWeekManualEvent,
  getShiftWeekRangeTitle,
  getShiftWeekSubtitle,
  getShiftWeekTableRows,
  getShiftWeekTableColumns,
  getTodayAnchorDate,
  initialShiftWeekCalendar,
  initialShiftWeekAnchorDate,
  initialShiftWeekDemoView,
  initialShiftWeekWorkspaceView,
  navigateShiftWeekAnchorDate,
  normalizeShiftWeekAnchorDate,
  reassignShiftWeekEvent,
  shiftWeekCalendarOptions,
  shiftWeekNewEventStatusOptions,
  shiftWeekNewEventTypeOptions,
  shiftResources,
  shiftWeekDemoViews,
  shiftWeekTeamMembers,
  shiftWeekViewLabels,
  type ShiftWeekDemoCalendar,
  type ShiftWeekDemoView,
  type ShiftWeekNewEventForm,
  type ShiftWeekWorkspaceView,
} from './data';
import {
  defineSchedulerShellElements,
  type SchedulerDialogSubmitDetail,
  type SchedulerHeaderCalendarChangeDetail,
  type SchedulerHeaderNavigateDetail,
  type SchedulerHeaderViewChangeDetail,
  type SchedulerHeaderWorkspaceChangeDetail,
} from './components';
import './styles.scss';

defineSchedulerShellElements();

const isDark = ref(currentTheme().isDark());
let disconnectTheme: (() => void) | undefined;

onMounted(() => {
  disconnectTheme = observeCurrentTheme((value) => {
    isDark.value = value;
  });
});
onBeforeUnmount(() => disconnectTheme?.());

const plugins = [EventSchedulerPlugin];
const tablePlugins = [AdvanceFilterPlugin, ColumnStretchPlugin, RowOddPlugin];
const tableColumns = getShiftWeekTableColumns();
const columns = ref([]);
const activeView = ref<ShiftWeekDemoView>(initialShiftWeekDemoView);
const workspaceView = ref<ShiftWeekWorkspaceView>(initialShiftWeekWorkspaceView);
const anchorDate = ref(initialShiftWeekAnchorDate);
const activeCalendar = ref<ShiftWeekDemoCalendar>(initialShiftWeekCalendar);
const selectedEventIds = ref<readonly EventSchedulerEntityId[]>([]);
const viewLabels = shiftWeekViewLabels;
const viewKeys = shiftWeekDemoViews;
const calendarOptions = shiftWeekCalendarOptions;
const teamMembers = shiftWeekTeamMembers;
const newEventStatusOptions = shiftWeekNewEventStatusOptions;
const newEventTypeOptions = shiftWeekNewEventTypeOptions;
const newEventForm = ref<ShiftWeekNewEventForm | null>(null);
const schedulerEvents = ref(createShiftWeekEvents(activeView.value, anchorDate.value));
const resources = ref(shiftResources.map((resource) => ({ ...resource })));
const filteredTableRows = computed(() => getShiftWeekTableRows(schedulerEvents.value));
const schedulerConfig = computed(() => createShiftWeekConfig(
  activeView.value,
  anchorDate.value,
  activeCalendar.value,
  selectedEventIds.value,
  [],
  workspaceView.value,
));
const rangeTitle = computed(() => getShiftWeekRangeTitle(activeView.value, anchorDate.value));
const rangeSubtitle = computed(() => getShiftWeekSubtitle(anchorDate.value, activeView.value));
const headerModel = computed(() => ({
  workspaceView: workspaceView.value,
  activeView: activeView.value,
  activeCalendar: activeCalendar.value,
  title: rangeTitle.value,
  subtitle: rangeSubtitle.value,
  views: viewKeys,
  viewLabels,
  calendarOptions,
}));
const dialogModel = computed(() => newEventForm.value ? ({
  form: newEventForm.value,
  teamMembers,
  typeOptions: newEventTypeOptions,
  statusOptions: newEventStatusOptions,
}) : null);

function setView(view: ShiftWeekDemoView, date = anchorDate.value) {
  activeView.value = view;
  if (view === 'resource') {
    workspaceView.value = 'resource';
    activeView.value = 'week';
  }
  anchorDate.value = normalizeShiftWeekAnchorDate(view, date);
  selectedEventIds.value = [];
  schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
}

function setWorkspace(view: ShiftWeekWorkspaceView) {
  workspaceView.value = view;
  if (view === 'resource') {
    anchorDate.value = normalizeShiftWeekAnchorDate(activeView.value, anchorDate.value);
    selectedEventIds.value = [];
    schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
  } else if (view === 'calendar' && activeView.value === 'resource') {
    activeView.value = 'week';
  }
}

function goPrevious() {
  anchorDate.value = navigateShiftWeekAnchorDate(activeView.value, anchorDate.value, -1);
  selectedEventIds.value = [];
  schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
}

function goNext() {
  anchorDate.value = navigateShiftWeekAnchorDate(activeView.value, anchorDate.value, 1);
  selectedEventIds.value = [];
  schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
}

function goToday() {
  anchorDate.value = getTodayAnchorDate(activeView.value);
  selectedEventIds.value = [];
  schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
}

function closeNewEvent() {
  newEventForm.value = null;
}

function submitNewEvent(form: ShiftWeekNewEventForm) {
  schedulerEvents.value = [
    ...schedulerEvents.value,
    createShiftWeekManualEvent(form),
  ];
  closeNewEvent();
}

function handleHeaderWorkspaceChange(event: CustomEvent<SchedulerHeaderWorkspaceChangeDetail>) {
  setWorkspace(event.detail.view);
}

function handleHeaderNavigate(event: CustomEvent<SchedulerHeaderNavigateDetail>) {
  handleNavigateRequest(event);
}

function handleHeaderViewChange(event: CustomEvent<SchedulerHeaderViewChangeDetail>) {
  setView(event.detail.view);
}

function handleHeaderCalendarChange(event: CustomEvent<SchedulerHeaderCalendarChangeDetail>) {
  activeCalendar.value = event.detail.calendar;
}

function handleDialogSubmit(event: CustomEvent<SchedulerDialogSubmitDetail>) {
  submitNewEvent(event.detail.form);
}

watch(activeCalendar, () => {
  selectedEventIds.value = [];
  schedulerEvents.value = createShiftWeekEvents(activeView.value, anchorDate.value);
});

function handleBeforeEventSelect(event: CustomEvent<EventSchedulerEventSelectedDetail>) {
  event.preventDefault();
  selectedEventIds.value = [...event.detail.eventIds];
}

function handleSchedulerEvents(event: CustomEvent) {
  schedulerEvents.value = applySourceChanges(schedulerEvents.value, event.detail.sourceChanges);
}

function handleOpenShiftAssignRequest(event: CustomEvent<EventSchedulerOpenShiftAssignRequestDetail>) {
  schedulerEvents.value = [
    ...schedulerEvents.value,
    createShiftWeekAssignedOpenShift(event.detail),
  ];
}

function handleResourceReassignRequest(event: CustomEvent<EventSchedulerResourceReassignRequestDetail>) {
  schedulerEvents.value = [
    ...reassignShiftWeekEvent(schedulerEvents.value, event.detail),
  ];
}

function handleNavigateRequest(event: CustomEvent<{ action: 'previous' | 'next' | 'today' }>) {
  if (event.detail.action === 'previous') {
    goPrevious();
  } else if (event.detail.action === 'next') {
    goNext();
  } else {
    goToday();
  }
}

function handleViewRequest(event: CustomEvent<{ view: ShiftWeekDemoView; date?: string }>) {
  if (event.detail.view === 'day' || event.detail.view === 'week' || event.detail.view === 'month' || event.detail.view === 'year' || event.detail.view === 'resource') {
    setView(event.detail.view, event.detail.date);
  }
}
</script>

// src/scheduler.react.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import { EventSchedulerPlugin, type EventSchedulerEntityId, type EventSchedulerEventEntity, type EventSchedulerEventSelectedDetail, type EventSchedulerOpenShiftAssignRequestDetail, type EventSchedulerResourceReassignRequestDetail } from '@revolist/scheduler';
import { AdvanceFilterPlugin, ColumnStretchPlugin, RowOddPlugin, applySourceChanges } from '@revolist/revogrid-pro';
import { currentTheme, observeCurrentTheme } from './shared/theme';
import {
  createShiftWeekAssignedOpenShift,
  createShiftWeekConfig,
  createShiftWeekEvents,
  createShiftWeekManualEvent,
  getShiftWeekRangeTitle,
  getShiftWeekSubtitle,
  getShiftWeekTableColumns,
  getShiftWeekTableRows,
  getTodayAnchorDate,
  initialShiftWeekCalendar,
  initialShiftWeekAnchorDate,
  initialShiftWeekDemoView,
  initialShiftWeekWorkspaceView,
  navigateShiftWeekAnchorDate,
  normalizeShiftWeekAnchorDate,
  reassignShiftWeekEvent,
  shiftWeekCalendarOptions,
  shiftWeekNewEventStatusOptions,
  shiftWeekNewEventTypeOptions,
  shiftResources,
  shiftWeekDemoViews,
  shiftWeekTeamMembers,
  shiftWeekViewLabels,
  type ShiftWeekDemoCalendar,
  type ShiftWeekDemoView,
  type ShiftWeekNewEventForm,
  type ShiftWeekWorkspaceView,
} from './data';
import {
  SCHEDULER_DIALOG_TAG,
  SCHEDULER_HEADER_TAG,
  defineSchedulerShellElements,
  type SchedulerDialogElement,
  type SchedulerDialogSubmitDetail,
  type SchedulerHeaderCalendarChangeDetail,
  type SchedulerHeaderElement,
  type SchedulerHeaderNavigateDetail,
  type SchedulerHeaderViewChangeDetail,
  type SchedulerHeaderWorkspaceChangeDetail,
} from './components';
import './styles.scss';

defineSchedulerShellElements();

export default function EventSchedulerShiftWeek() {
  const shellRef = useRef<HTMLElement | null>(null);
  const gridRef = useRef<HTMLRevoGridElement | null>(null);
  const headerRef = useRef<SchedulerHeaderElement | null>(null);
  const dialogRef = useRef<SchedulerDialogElement | null>(null);
  const [isDark, setIsDark] = useState(() => currentTheme().isDark());
  const [activeView, setActiveViewState] = useState<ShiftWeekDemoView>(initialShiftWeekDemoView);
  const [workspaceView, setWorkspaceView] = useState<ShiftWeekWorkspaceView>(initialShiftWeekWorkspaceView);
  const [activeCalendar, setActiveCalendar] = useState<ShiftWeekDemoCalendar>(initialShiftWeekCalendar);
  const [anchorDate, setAnchorDate] = useState(initialShiftWeekAnchorDate);
  const [events, setEvents] = useState<readonly EventSchedulerEventEntity[]>(() => createShiftWeekEvents(initialShiftWeekDemoView, initialShiftWeekAnchorDate));
  const [selectedEventIds, setSelectedEventIds] = useState<readonly EventSchedulerEntityId[]>([]);
  const [newEventForm, setNewEventForm] = useState<ShiftWeekNewEventForm | null>(null);
  const plugins = useMemo(() => [EventSchedulerPlugin], []);
  const tablePlugins = useMemo(() => [AdvanceFilterPlugin, ColumnStretchPlugin, RowOddPlugin], []);
  const tableColumns = useMemo(() => getShiftWeekTableColumns(), []);
  const columnTypes = useMemo(() => ({}), []);
  const additionalData = useMemo(() => ({}), []);
  const resources = useMemo(() => shiftResources.map((resource) => ({ ...resource })), []);
  const schedulerConfig = useMemo(
    () => createShiftWeekConfig(activeView, anchorDate, activeCalendar, selectedEventIds, [], workspaceView),
    [activeView, anchorDate, activeCalendar, selectedEventIds, workspaceView],
  );
  const rangeTitle = useMemo(() => getShiftWeekRangeTitle(activeView, anchorDate), [activeView, anchorDate]);
  const rangeSubtitle = useMemo(() => getShiftWeekSubtitle(anchorDate, activeView), [activeView, anchorDate]);
  const tableRows = useMemo(() => getShiftWeekTableRows(events), [events]);
  const headerModel = useMemo(() => ({
    workspaceView,
    activeView,
    activeCalendar,
    title: rangeTitle,
    subtitle: rangeSubtitle,
    views: shiftWeekDemoViews,
    viewLabels: shiftWeekViewLabels,
    calendarOptions: shiftWeekCalendarOptions,
  }), [workspaceView, activeView, activeCalendar, rangeTitle, rangeSubtitle]);
  const dialogModel = useMemo(() => newEventForm ? ({
    form: newEventForm,
    teamMembers: shiftWeekTeamMembers,
    typeOptions: shiftWeekNewEventTypeOptions,
    statusOptions: shiftWeekNewEventStatusOptions,
  }) : null, [newEventForm]);

  useEffect(() => observeCurrentTheme(setIsDark), []);

  const resetEvents = useCallback((view: ShiftWeekDemoView, date: string) => {
    setEvents(createShiftWeekEvents(view, date));
  }, []);

  const setView = useCallback((view: ShiftWeekDemoView, date = anchorDate) => {
    const nextView = view === 'resource' ? 'week' : view;
    const normalizedAnchor = normalizeShiftWeekAnchorDate(view, date);
    setActiveViewState(nextView);
    if (view === 'resource') {
      setWorkspaceView('resource');
    }
    setAnchorDate(normalizedAnchor);
    setSelectedEventIds([]);
    resetEvents(nextView, normalizedAnchor);
  }, [anchorDate, resetEvents]);

  const setWorkspace = useCallback((view: ShiftWeekWorkspaceView) => {
    setWorkspaceView(view);
    if (view === 'resource') {
      const normalizedAnchor = normalizeShiftWeekAnchorDate(activeView, anchorDate);
      setAnchorDate(normalizedAnchor);
      setSelectedEventIds([]);
      resetEvents(activeView, normalizedAnchor);
      return;
    }
    if (view === 'calendar' && activeView === 'resource') {
      setActiveViewState('week');
    }
  }, [activeView, anchorDate, resetEvents]);

  const goPrevious = useCallback(() => {
    const nextAnchor = navigateShiftWeekAnchorDate(activeView, anchorDate, -1);
    setAnchorDate(nextAnchor);
    setSelectedEventIds([]);
    resetEvents(activeView, nextAnchor);
  }, [activeView, anchorDate, resetEvents]);

  const goNext = useCallback(() => {
    const nextAnchor = navigateShiftWeekAnchorDate(activeView, anchorDate, 1);
    setAnchorDate(nextAnchor);
    setSelectedEventIds([]);
    resetEvents(activeView, nextAnchor);
  }, [activeView, anchorDate, resetEvents]);

  const goToday = useCallback(() => {
    const nextAnchor = getTodayAnchorDate(activeView);
    setAnchorDate(nextAnchor);
    setSelectedEventIds([]);
    resetEvents(activeView, nextAnchor);
  }, [activeView, resetEvents]);

  const setCalendar = useCallback((calendar: ShiftWeekDemoCalendar) => {
    setActiveCalendar(calendar);
    setSelectedEventIds([]);
    resetEvents(activeView, anchorDate);
  }, [activeView, anchorDate, resetEvents]);

  useEffect(() => {
    if (headerRef.current) headerRef.current.model = headerModel;
  }, [headerModel]);

  useEffect(() => {
    if (dialogRef.current) dialogRef.current.model = dialogModel;
  }, [dialogModel]);

  useEffect(() => {
    const shell = shellRef.current;
    if (!shell) return undefined;
    const handleWorkspace = (event: Event) => setWorkspace((event as CustomEvent<SchedulerHeaderWorkspaceChangeDetail>).detail.view);
    const handleNavigate = (event: Event) => {
      const { action } = (event as CustomEvent<SchedulerHeaderNavigateDetail>).detail;
      if (action === 'previous') goPrevious();
      else if (action === 'next') goNext();
      else goToday();
    };
    const handleView = (event: Event) => setView((event as CustomEvent<SchedulerHeaderViewChangeDetail>).detail.view);
    const handleCalendar = (event: Event) => setCalendar((event as CustomEvent<SchedulerHeaderCalendarChangeDetail>).detail.calendar);
    const handleDialogClose = () => setNewEventForm(null);
    const handleDialogSubmit = (event: Event) => {
      const { form } = (event as CustomEvent<SchedulerDialogSubmitDetail>).detail;
      setEvents((currentEvents) => [...currentEvents, createShiftWeekManualEvent(form)]);
      setNewEventForm(null);
    };
    shell.addEventListener('scheduler-header-workspace-change', handleWorkspace);
    shell.addEventListener('scheduler-header-navigate', handleNavigate);
    shell.addEventListener('scheduler-header-view-change', handleView);
    shell.addEventListener('scheduler-header-calendar-change', handleCalendar);
    shell.addEventListener('scheduler-dialog-close', handleDialogClose);
    shell.addEventListener('scheduler-dialog-submit', handleDialogSubmit);
    return () => {
      shell.removeEventListener('scheduler-header-workspace-change', handleWorkspace);
      shell.removeEventListener('scheduler-header-navigate', handleNavigate);
      shell.removeEventListener('scheduler-header-view-change', handleView);
      shell.removeEventListener('scheduler-header-calendar-change', handleCalendar);
      shell.removeEventListener('scheduler-dialog-close', handleDialogClose);
      shell.removeEventListener('scheduler-dialog-submit', handleDialogSubmit);
    };
  }, [goNext, goPrevious, goToday, setCalendar, setView, setWorkspace]);

  useEffect(() => {
    const grid = gridRef.current;
    if (!grid) return undefined;
    const syncEvents = (event: Event) => {
      setEvents(current => applySourceChanges(current, (event as CustomEvent).detail.sourceChanges));
    };
    const handleBeforeEventSelect = (event: Event) => {
      event.preventDefault();
      setSelectedEventIds([...(event as CustomEvent<EventSchedulerEventSelectedDetail>).detail.eventIds]);
    };
    const handleNavigateRequest = (event: Event) => {
      const action = (event as CustomEvent<{ action: 'previous' | 'next' | 'today' }>).detail.action;
      if (action === 'previous') {
        goPrevious();
      } else if (action === 'next') {
        goNext();
      } else {
        goToday();
      }
    };
    const handleViewRequest = (event: Event) => {
      const { view, date } = (event as CustomEvent<{ view: ShiftWeekDemoView; date?: string }>).detail;
      if (view === 'day' || view === 'week' || view === 'month' || view === 'year' || view === 'resource') {
        setView(view, date);
      }
    };
    const handleOpenShiftAssignRequest = (event: Event) => {
      setEvents((currentEvents) => [
        ...currentEvents,
        createShiftWeekAssignedOpenShift((event as CustomEvent<EventSchedulerOpenShiftAssignRequestDetail>).detail),
      ]);
    };
    const handleResourceReassignRequest = (event: Event) => {
      setEvents((currentEvents) => [
        ...reassignShiftWeekEvent(
          currentEvents,
          (event as CustomEvent<EventSchedulerResourceReassignRequestDetail>).detail,
        ),
      ]);
    };
    grid.addEventListener('gridedit', syncEvents);
    grid.addEventListener('event-scheduler-before-event-select', handleBeforeEventSelect);
    grid.addEventListener('event-scheduler-navigate-request', handleNavigateRequest);
    grid.addEventListener('event-scheduler-open-shift-assign-request', handleOpenShiftAssignRequest);
    grid.addEventListener('event-scheduler-resource-reassign-request', handleResourceReassignRequest);
    grid.addEventListener('event-scheduler-view-request', handleViewRequest);
    return () => {
      grid.removeEventListener('gridedit', syncEvents);
      grid.removeEventListener('event-scheduler-before-event-select', handleBeforeEventSelect);
      grid.removeEventListener('event-scheduler-navigate-request', handleNavigateRequest);
      grid.removeEventListener('event-scheduler-open-shift-assign-request', handleOpenShiftAssignRequest);
      grid.removeEventListener('event-scheduler-resource-reassign-request', handleResourceReassignRequest);
      grid.removeEventListener('event-scheduler-view-request', handleViewRequest);
    };
  }, [goNext, goPrevious, goToday, setView]);

  return (
    <section ref={shellRef} className="event-scheduler-shift-week-demo">
      <div className="event-scheduler-shift-week-main">
        {React.createElement(SCHEDULER_HEADER_TAG, { ref: headerRef })}
        {workspaceView === 'table' ? (
          <RevoGrid
            theme={isDark ? 'darkMaterial' : 'material'}
            hideAttribution
            readonly
            plugins={tablePlugins}
            filter={{}}
            source={tableRows}
            columns={tableColumns}
            className="event-scheduler-shift-week-table"
          />
        ) : (
          <RevoGrid
              ref={gridRef}
              className="event-scheduler-shift-week-grid"
              theme={isDark ? 'darkMaterial' : 'material'}
              hideAttribution
              plugins={plugins}
              source={events}
              columns={[]}
              columnTypes={columnTypes}
              additionalData={additionalData}
              eventScheduler={schedulerConfig}
              eventSchedulerResources={resources}
          />
        )}
      </div>
      {React.createElement(SCHEDULER_DIALOG_TAG, { ref: dialogRef })}
    </section>
  );
}
